#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

'''
    Main program for np (Network Ping)

    Copyright (C) 2015
    Joseba Martos <joseba@otzarri.net>

    This file is part of np (Network Ping)
    Web site: http://otzarri.net/np

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import nplib

show_alive = True
show_down = False

pingers = list()

nplib.NetDiscover.discover_working_networks()
networks = nplib.NetDiscover.networks

for network in networks:
    pingers.append(nplib.Pinger(network))

for pinger in pingers:
    pinger.run()

if show_down:
    print('\r\nHosts down (all):')
    for host in sorted(nplib.Pinger.hosts_down):
        print(host)
    print('')

if show_alive:
    print('\r\nHosts alive (all):')
    for host in sorted(nplib.Pinger.hosts_up):
        print(host)
    print('')
